kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
archiveSize: 25 # Size of tar archive files in GBs
mirror:
  platform:
    channels:
    - name: stable-4.19
      type: ocp
      minVersion: 4.19.9
      maxVersion: 4.19.9
    graph: true
